# Generated by Django 6.0.3 on 2026-03-08 03:53

import django.core.validators
import django.db.models.deletion
import sessions.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('media_attached', 'Media Attached'), ('queued_ml', 'Queued ML'), ('processing_ml', 'Processing ML'), ('ml_ready', 'ML Ready'), ('processing_coach', 'Processing Coach'), ('ready', 'Ready'), ('coach_failed', 'Coach Failed'), ('failed', 'Failed')], db_index=True, default='draft', max_length=32)),
                ('video_file', models.FileField(blank=True, max_length=512, null=True, upload_to='sessions/videos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4']), sessions.models.MaxFileSizeValidator(label='Video file', max_bytes=524288000)])),
                ('supplementary_pdf_1', models.FileField(blank=True, max_length=512, null=True, upload_to='sessions/assets/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), sessions.models.MaxFileSizeValidator(label='Supplementary PDF', max_bytes=26214400)])),
                ('supplementary_pdf_2', models.FileField(blank=True, max_length=512, null=True, upload_to='sessions/assets/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), sessions.models.MaxFileSizeValidator(label='Supplementary PDF', max_bytes=26214400)])),
                ('supplementary_pdf_3', models.FileField(blank=True, max_length=512, null=True, upload_to='sessions/assets/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), sessions.models.MaxFileSizeValidator(label='Supplementary PDF', max_bytes=26214400)])),
                ('speaker_context', models.TextField(blank=True, default='')),
                ('ml_task_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('coach_task_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'created_at'], name='coach_sess_user_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status', 'draft'), models.Q(('video_file__isnull', False), models.Q(('video_file', ''), _negated=True)), _connector='OR'), name='coach_sess_non_draft_has_video')],
            },
        ),
    ]
