# Generated by Django 6.0.3 on 2026-03-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachingsession',
            name='title',
            field=models.CharField(default='Untitled Session', max_length=255),
        ),
    ]
