# Generated by Django 6.0.3 on 2026-03-08 11:30

import django.core.validators
from django.db import migrations, models

import sessions.models


class Migration(migrations.Migration):

    dependencies = [
        ("coach_sessions", "0002_coachingsession_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coachingsession",
            name="video_file",
            field=models.FileField(
                blank=True,
                max_length=512,
                null=True,
                upload_to="sessions/videos/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "webm"]
                    ),
                    sessions.models.MaxFileSizeValidator(
                        label="Video file", max_bytes=524288000
                    ),
                ],
            ),
        ),
    ]
