# Generated by Django 6.0.3 on 2026-03-08 07:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_sessions', '0002_coachingsession_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachAgentExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('execution_index', models.PositiveIntegerField()),
                ('agent_kind', models.CharField(choices=[('subagent', 'Subagent'), ('flagship_periodic', 'Flagship Periodic'), ('flagship_final', 'Flagship Final')], max_length=32)),
                ('agent_name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('window_start_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('window_end_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('input_seq_from', models.PositiveBigIntegerField(blank=True, null=True)),
                ('input_seq_to', models.PositiveBigIntegerField(blank=True, null=True)),
                ('output_seq_to', models.PositiveBigIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('execution_index', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='CoachOrchestrationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_index', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16)),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('latest_ledger_sequence', models.PositiveBigIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_runs', to='coach_sessions.coachingsession')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CoachLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveBigIntegerField()),
                ('entry_kind', models.CharField(choices=[('subagent_note', 'Subagent Note'), ('flagship_impression', 'Flagship Impression'), ('flagship_final', 'Flagship Final')], max_length=32)),
                ('agent_kind', models.CharField(blank=True, choices=[('subagent', 'Subagent'), ('flagship_periodic', 'Flagship Periodic'), ('flagship_final', 'Flagship Final')], max_length=32, null=True)),
                ('agent_name', models.CharField(blank=True, default='', max_length=128)),
                ('window_start_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('window_end_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('content', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='coach_sessions.coachagentexecution')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='coach_sessions.coachorchestrationrun')),
            ],
            options={
                'ordering': ('sequence', 'created_at'),
            },
        ),
        migrations.AddField(
            model_name='coachagentexecution',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_executions', to='coach_sessions.coachorchestrationrun'),
        ),
        migrations.AddIndex(
            model_name='coachorchestrationrun',
            index=models.Index(fields=['session', 'created_at'], name='coach_run_sess_created_idx'),
        ),
        migrations.AddIndex(
            model_name='coachorchestrationrun',
            index=models.Index(fields=['session', 'status'], name='coach_run_sess_status_idx'),
        ),
        migrations.AddIndex(
            model_name='coachorchestrationrun',
            index=models.Index(fields=['session', 'run_index'], name='coach_run_sess_runidx_idx'),
        ),
        migrations.AddConstraint(
            model_name='coachorchestrationrun',
            constraint=models.UniqueConstraint(fields=('session', 'run_index'), name='coach_run_session_idx_uq'),
        ),
        migrations.AddConstraint(
            model_name='coachorchestrationrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'processing'])), fields=('session',), name='coach_run_active_uq'),
        ),
        migrations.AddIndex(
            model_name='coachledgerentry',
            index=models.Index(fields=['run', 'sequence'], name='coach_ledger_run_seq_idx'),
        ),
        migrations.AddIndex(
            model_name='coachledgerentry',
            index=models.Index(fields=['run', 'created_at'], name='coach_ledger_run_created_idx'),
        ),
        migrations.AddIndex(
            model_name='coachledgerentry',
            index=models.Index(fields=['run', 'entry_kind'], name='coach_ledger_run_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='coachledgerentry',
            constraint=models.UniqueConstraint(fields=('run', 'sequence'), name='coach_ledger_run_seq_uq'),
        ),
        migrations.AddIndex(
            model_name='coachagentexecution',
            index=models.Index(fields=['run', 'execution_index'], name='coach_agent_run_exec_idx'),
        ),
        migrations.AddIndex(
            model_name='coachagentexecution',
            index=models.Index(fields=['run', 'status'], name='coach_agent_run_status_idx'),
        ),
        migrations.AddIndex(
            model_name='coachagentexecution',
            index=models.Index(fields=['run', 'created_at'], name='coach_agent_run_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='coachagentexecution',
            constraint=models.UniqueConstraint(fields=('run', 'execution_index'), name='coach_agent_run_exec_uq'),
        ),
        migrations.AddConstraint(
            model_name='coachagentexecution',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('window_end_ms__isnull', True), ('window_start_ms__isnull', True)), models.Q(('window_end_ms__isnull', False), ('window_start_ms__isnull', False), ('window_start_ms__lte', models.F('window_end_ms'))), _connector='OR'), name='coach_agent_window_bounds_ck'),
        ),
    ]
