# Generated by Django 6.0.3 on 2026-03-08 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach_sessions', '0003_alter_coachingsession_video_file'),
        ('coach_sessions', '0003_coachagentexecution_coachorchestrationrun_and_more'),
    ]

    operations = [
    ]
